[package]
name = "blink-rs"
version = "0.1.0"
edition = "2021"
authors = ["Lílian Ferreira de Freitas"]

[dependencies]

[profile.dev]
lto = true
opt-level = "s"
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
